### ISSUE TITLE
logs do not arrive in papertrail

### ISSUE THREAD

**Issue by thomasspiesser** [keboola/serverless-papertrail-logging#5]
Hey guys,

I'm checking out your plugin and would like to use it since it seems really convenient and smartly done. Cudos. Unfortunately, I'm facing the issue that all seems to be in order except that no logs appear in papertrail 😀 

My setup:

`yarn add @keboola/serverless-papertrail-logging --dev`

// serverless.yml
```
service: test

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          authorizer: aws_iam

custom:
  papertrail:
    port: XYZ
    host: logsX.papertrailapp.com
    
plugins:
  - '@keboola/serverless-papertrail-logging'
```

`sls deploy` output
```
Serverless: Creating temporary logger function...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Creating log subscriptions...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (3.7 KB)...
Serverless: Validating template...
Serverless: Updating Stack...
Serverless: Checking Stack update progress...
............
Serverless: Stack update finished...
Service Information
service: test
stage: dev
region: eu-central-1
stack: test-dev
api keys:
  None
endpoints:
  GET - https://XXX.execute-api.eu-central-1.amazonaws.com/dev/hello
functions:
  hello: test-dev-hello
  papertrailLogger: test-dev-papertrailLogger
Serverless: Removing temporary logger function
```

so that seems fine.

in Cloudwatch I can see the 2 log groups for the 2 functions. the test function also shows an active subscription from the `Lambda (test-dev-papertrailLogger)` function, which also seems fine to me.

Here is my `hello.handler.js`

```
module.exports.hello = (event, context, callback) => {
  console.log('This is a log message');
  throw new Error('this is the error message');
  const response = {
    statusCode: 200,
    body: JSON.stringify({
      message: 'Go Serverless v1.0! Your function executed successfully!',
      input: event,
    }),
  };
  callback(null, response);
};
```

Any ideas where to go from here or what i'm doing wrong?

Cheers!
